using System.Text.Json;
using System.Text.Json.Serialization;
using ZeroAlloc.ValueObjects;

namespace Rag.NET.Models;

/// <summary>
/// A document's stable identifier — the value chunks, sections, and vector-store records are all
/// keyed by. A thin wrapper over a non-empty string rather than a raw <see cref="string"/>, so a
/// document id can't be accidentally passed where some other identifier is expected.
/// </summary>
[JsonConverter(typeof(DocumentIdJsonConverter))]
[ValueObject]
public sealed partial class DocumentId
{
    private readonly string _value;

    /// <summary>The underlying string value.</summary>
    [EqualityMember]
    public string Value => _value;

    /// <summary>Wraps <paramref name="value"/> as a document id.</summary>
    /// <exception cref="ArgumentException"><paramref name="value"/> is null or empty.</exception>
    public DocumentId(string value)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
        _value = value;
    }

    // ToString() => Value is generated by ZeroAlloc.ValueObjects (single-property raw-value form).

    /// <summary>Unwraps <paramref name="id"/> to its underlying string — always succeeds.</summary>
    public static implicit operator string(DocumentId id) => id._value;

    /// <summary>Wraps <paramref name="s"/> as a document id — equivalent to the constructor.</summary>
    /// <exception cref="ArgumentException"><paramref name="s"/> is null or empty.</exception>
    public static explicit operator DocumentId(string s) => new(s);

    private sealed class DocumentIdJsonConverter : JsonConverter<DocumentId>
    {
        public override DocumentId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (string.IsNullOrEmpty(value))
                throw new JsonException("DocumentId cannot be null or empty.");
            return new(value);
        }

        public override void Write(Utf8JsonWriter writer, DocumentId value, JsonSerializerOptions options)
            => writer.WriteStringValue(value._value);
    }
}
