using System.Text.Json;
using System.Text.Json.Serialization;
using ZeroAlloc.ValueObjects;

namespace Rag.NET.Models;

/// <summary>
/// An item's identifier within a data provider's own source system — a page id, ticket number, or
/// file id, depending on the connector. Used together with <see cref="ProviderId"/> as the key for
/// incremental-sync content-hash tracking (see <c>IContentHashStore</c>). A thin wrapper over a
/// non-empty string, so an entry id can't be accidentally passed where some other identifier is
/// expected.
/// </summary>
[JsonConverter(typeof(EntryIdJsonConverter))]
[ValueObject]
public sealed partial class EntryId
{
    private readonly string _value;

    /// <summary>The underlying string value.</summary>
    [EqualityMember]
    public string Value => _value;

    /// <summary>Wraps <paramref name="value"/> as an entry id.</summary>
    /// <exception cref="ArgumentException"><paramref name="value"/> is null or empty.</exception>
    public EntryId(string value)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
        _value = value;
    }

    // ToString() => Value is generated by ZeroAlloc.ValueObjects (single-property raw-value form).

    /// <summary>Unwraps <paramref name="id"/> to its underlying string — always succeeds.</summary>
    public static implicit operator string(EntryId id) => id._value;

    /// <summary>Wraps <paramref name="s"/> as an entry id — equivalent to the constructor.</summary>
    /// <exception cref="ArgumentException"><paramref name="s"/> is null or empty.</exception>
    public static explicit operator EntryId(string s) => new(s);

    private sealed class EntryIdJsonConverter : JsonConverter<EntryId>
    {
        public override EntryId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (string.IsNullOrEmpty(value))
                throw new JsonException("EntryId cannot be null or empty.");
            return new(value);
        }

        public override void Write(Utf8JsonWriter writer, EntryId value, JsonSerializerOptions options)
            => writer.WriteStringValue(value._value);
    }
}
