using System.Text.Json;
using System.Text.Json.Serialization;
using ZeroAlloc.ValueObjects;

namespace Rag.NET.Models;

/// <summary>
/// Identifies the data-provider connector a document or entry came from (for example
/// <c>"confluence"</c>, <c>"jira"</c>). Written centrally at ingest time as reserved chunk
/// metadata (see <see cref="ReservedMetadataKeys.ProviderId"/>) and used together with
/// <see cref="EntryId"/> as the key for incremental-sync content-hash tracking. A thin wrapper
/// over a non-empty string, so a provider id can't be accidentally passed where some other
/// identifier is expected.
/// </summary>
[JsonConverter(typeof(ProviderIdJsonConverter))]
[ValueObject]
public sealed partial class ProviderId
{
    private readonly string _value;

    /// <summary>The underlying string value.</summary>
    [EqualityMember]
    public string Value => _value;

    /// <summary>Wraps <paramref name="value"/> as a provider id.</summary>
    /// <exception cref="ArgumentException"><paramref name="value"/> is null or empty.</exception>
    public ProviderId(string value)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
        _value = value;
    }

    // ToString() => Value is generated by ZeroAlloc.ValueObjects (single-property raw-value form).

    /// <summary>Unwraps <paramref name="id"/> to its underlying string — always succeeds.</summary>
    public static implicit operator string(ProviderId id) => id._value;

    /// <summary>Wraps <paramref name="s"/> as a provider id — equivalent to the constructor.</summary>
    /// <exception cref="ArgumentException"><paramref name="s"/> is null or empty.</exception>
    public static explicit operator ProviderId(string s) => new(s);

    private sealed class ProviderIdJsonConverter : JsonConverter<ProviderId>
    {
        public override ProviderId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (string.IsNullOrEmpty(value))
                throw new JsonException("ProviderId cannot be null or empty.");
            return new(value);
        }

        public override void Write(Utf8JsonWriter writer, ProviderId value, JsonSerializerOptions options)
            => writer.WriteStringValue(value._value);
    }
}
