using System.Text.Json;
using System.Text.Json.Serialization;
using ZeroAlloc.ValueObjects;

namespace Rag.NET.Models;

/// <summary>
/// Scoping key for a conversation, used by persistent <c>IConversationMemory</c> implementations
/// to namespace stored exchanges (for example per-user or per-conversation). A thin wrapper over a
/// non-empty string, so a session id can't be accidentally passed where some other identifier is
/// expected.
/// </summary>
[JsonConverter(typeof(SessionIdJsonConverter))]
[ValueObject]
public sealed partial class SessionId
{
    private readonly string _value;

    /// <summary>The underlying string value.</summary>
    [EqualityMember]
    public string Value => _value;

    /// <summary>Wraps <paramref name="value"/> as a session id.</summary>
    /// <exception cref="ArgumentException"><paramref name="value"/> is null or empty.</exception>
    public SessionId(string value)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
        _value = value;
    }

    // ToString() => Value is generated by ZeroAlloc.ValueObjects (single-property raw-value form).

    /// <summary>Unwraps <paramref name="id"/> to its underlying string — always succeeds.</summary>
    public static implicit operator string(SessionId id) => id._value;

    /// <summary>Wraps <paramref name="s"/> as a session id — equivalent to the constructor.</summary>
    /// <exception cref="ArgumentException"><paramref name="s"/> is null or empty.</exception>
    public static explicit operator SessionId(string s) => new(s);

    private sealed class SessionIdJsonConverter : JsonConverter<SessionId>
    {
        public override SessionId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (string.IsNullOrEmpty(value))
                throw new JsonException("SessionId cannot be null or empty.");
            return new(value);
        }

        public override void Write(Utf8JsonWriter writer, SessionId value, JsonSerializerOptions options)
            => writer.WriteStringValue(value._value);
    }
}
