<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rag.NET.Parsers.Word</RootNamespace>
    <PackageId>Rag.NET.Parsers.Word</PackageId>
    <Description>Word document parser for Rag.NET</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rag.NET\Rag.NET.csproj" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.*" />
  </ItemGroup>

</Project>
