using Microsoft.Extensions.DependencyInjection;
using Rag.NET.Abstractions;
using Rag.NET.HyDE;
using Rag.NET.Models.Options;
using Rag.NET.MultiQuery;

namespace Rag.NET.QueryTechniques;

public static class RagBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="LlmQueryExpander"/> as the <see cref="IQueryExpander"/>.
    /// When registered, the pipeline expands each query into
    /// <see cref="MultiQueryOptions.VariantCount"/> alternatives, fans out to the vector store
    /// in parallel, and merges deduplicated results.
    /// </summary>
    /// <remarks>
    /// Requires <c>IChatClient</c> to be registered in DI.
    /// Per-call opt-out: pass <c>new RetrievalOptions { UseMultiQuery = false }</c>.
    /// </remarks>
    /// <param name="builder">The RAG builder.</param>
    /// <param name="configure">Optional delegate to configure <see cref="MultiQueryOptions"/>.</param>
    public static TBuilder UseMultiQueryRetrieval<TBuilder>(this TBuilder builder, Action<MultiQueryOptions>? configure = null)
        where TBuilder : IRagBuilder
    {
        var options = new MultiQueryOptions();
        configure?.Invoke(options);
        builder.Services.AddSingleton(options);
        builder.Services.AddSingleton<IQueryExpander, LlmQueryExpander>();
        return builder;
    }

    /// <summary>
    /// Registers <see cref="LlmHypotheticalDocumentGenerator"/> as the <see cref="IHypotheticalDocumentGenerator"/>.
    /// When registered, the retriever embeds a hypothetical document generated by the LLM
    /// instead of the raw query, improving recall for asymmetric retrieval (short query vs. long document).
    /// </summary>
    /// <remarks>
    /// Requires <c>IChatClient</c> to be registered in DI.
    /// Per-call opt-out: pass <c>new RetrievalOptions { UseHyde = false }</c>.
    /// </remarks>
    /// <param name="builder">The RAG builder.</param>
    /// <param name="configure">Optional delegate to configure <see cref="HydeOptions"/>.</param>
    public static TBuilder UseHyde<TBuilder>(this TBuilder builder, Action<HydeOptions>? configure = null)
        where TBuilder : IRagBuilder
    {
        var options = new HydeOptions();
        configure?.Invoke(options);
        builder.Services.AddSingleton(options);
        builder.Services.AddSingleton<IHypotheticalDocumentGenerator, LlmHypotheticalDocumentGenerator>();
        return builder;
    }
}
