<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rag.NET.Parsers.Html</RootNamespace>
    <PackageId>Rag.NET.Parsers.Html</PackageId>
    <Description>HTML document parser for Rag.NET</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rag.NET.Abstractions\Rag.NET.Abstractions.csproj" />
    <PackageReference Include="AngleSharp" Version="1.*" />
  </ItemGroup>

</Project>
