using Microsoft.Extensions.DependencyInjection;
using Rag.NET.Abstractions;
using Rag.NET.DependencyInjection;
using Rag.NET.Models;
using Xunit;

namespace Rag.NET.Parsers.Pdf.Tests;

/// <summary>
/// Parser-level tests over embedded PDF fixtures:
/// - sample.pdf — pre-existing prose fixture shared with the integration tests.
/// - sample-table.pdf — generated by <see cref="TableFixtureGenerator"/> (see its provenance doc).
/// </summary>
public class PdfDocumentParserTests
{
    private static DocumentMetadata CreateMetadata() => new()
    {
        DocumentId = new DocumentId("pdf-1"),
        FileName = "test.pdf",
        ContentType = "application/pdf",
    };

    private static Stream OpenResource(string fileName)
    {
        var assembly = typeof(PdfDocumentParserTests).Assembly;
        var resourceName = $"Rag.NET.Parsers.Pdf.Tests.Resources.{fileName}";
        return assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' not found.");
    }

    private static async Task<List<DocumentSection>> ParseAsync(PdfDocumentParser parser, Stream stream)
    {
        var sections = new List<DocumentSection>();
        await foreach (var section in parser.ParseAsync(stream, CreateMetadata(), TestContext.Current.CancellationToken))
        {
            sections.Add(section);
        }

        return sections;
    }

    [Fact]
    public async Task Parse_TablePdf_EmitsTableSection()
    {
        var sut = new PdfDocumentParser();
        await using var stream = OpenResource("sample-table.pdf");

        var sections = await ParseAsync(sut, stream);

        var table = Assert.Single(sections, s => string.Equals(s.Heading, "table", StringComparison.Ordinal));
        Assert.Equal(1, table.PageNumber);
        Assert.Equal("| Name | Age | City |\n| --- | --- | --- |\n| Alice | 30 | Paris |\n| Bob | 25 | London |", table.Text);
    }

    [Fact]
    public async Task Parse_TablePdf_ProseExcludesTableWords()
    {
        var sut = new PdfDocumentParser();
        await using var stream = OpenResource("sample-table.pdf");

        var sections = await ParseAsync(sut, stream);

        // Document order: prose is partitioned around the table into separate sections
        // (above → table → below), each joined with spaces in reading order; whitespace
        // differs from the legacy page.Text concatenation by design.
        Assert.Equal(3, sections.Count);
        Assert.Equal("Introduction", sections[0].Text);
        Assert.Null(sections[0].Heading);
        Assert.Equal(0, sections[0].SectionIndex);
        Assert.Equal("table", sections[1].Heading);
        Assert.Equal(1, sections[1].SectionIndex);
        Assert.Equal("Conclusion", sections[2].Text);
        Assert.Null(sections[2].Heading);
        Assert.Equal(2, sections[2].SectionIndex);
    }

    [Fact]
    public async Task Parse_ProsePdf_BehaviorPreserved()
    {
        // sample.pdf contains no table geometry: with table extraction on (default), pages
        // without detected tables emit the exact legacy page.Text sections.
        var withTables = new PdfDocumentParser();
        var legacy = new PdfDocumentParser(new PdfParserOptions { ExtractTables = false });

        await using var streamA = OpenResource("sample.pdf");
        var defaultSections = await ParseAsync(withTables, streamA);
        await using var streamB = OpenResource("sample.pdf");
        var legacySections = await ParseAsync(legacy, streamB);

        Assert.NotEmpty(defaultSections);
        Assert.Equal(legacySections, defaultSections);
    }

    [Fact]
    public async Task Parse_ExtractTablesFalse_AllProse()
    {
        var sut = new PdfDocumentParser(new PdfParserOptions { ExtractTables = false });
        await using var stream = OpenResource("sample-table.pdf");

        var sections = await ParseAsync(sut, stream);

        var section = Assert.Single(sections);
        Assert.Null(section.Heading);
        Assert.Contains("Alice", section.Text, StringComparison.Ordinal);
        Assert.DoesNotContain("|", section.Text, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Fixture_MatchesGenerator()
    {
        // Ties the checked-in sample-table.pdf to TableFixtureGenerator: regenerated bytes
        // must parse to the same sections (byte-identity is not required — the PDF trailer
        // may differ across builder runs).
        var sut = new PdfDocumentParser();
        await using var fixtureStream = OpenResource("sample-table.pdf");
        var fromFixture = await ParseAsync(sut, fixtureStream);
        using var generatedStream = new MemoryStream(TableFixtureGenerator.Generate());
        var fromGenerator = await ParseAsync(sut, generatedStream);

        Assert.Equal(fromFixture, fromGenerator);
    }

    // ── DI ───────────────────────────────────────────────────────────────────

    [Fact]
    public void AddPdfParser_Configure_AppliesOptions()
    {
        var services = new ServiceCollection();
        var builder = new RagBuilder(services);

        builder.AddPdfParser(o => o.ExtractTables = false);

        using var provider = services.BuildServiceProvider();
        var options = provider.GetRequiredService<PdfParserOptions>();
        Assert.False(options.ExtractTables);
        var parser = Assert.Single(provider.GetServices<IDocumentParser>());
        Assert.IsType<PdfDocumentParser>(parser);
    }

    [Fact]
    public void AddPdfParser_Parameterless_StillRegisters()
    {
        var services = new ServiceCollection();
        var builder = new RagBuilder(services);

        builder.AddPdfParser();

        using var provider = services.BuildServiceProvider();
        var parser = Assert.Single(provider.GetServices<IDocumentParser>());
        Assert.IsType<PdfDocumentParser>(parser);
    }

    [Theory]
    [InlineData(0, 2)]
    [InlineData(3, 0)]
    public void AddPdfParser_InvalidCounts_Throws(int minRows, int minColumns)
    {
        var services = new ServiceCollection();
        var builder = new RagBuilder(services);

        Assert.Throws<ArgumentOutOfRangeException>(() =>
            builder.AddPdfParser(o =>
            {
                o.MinTableRows = minRows;
                o.MinTableColumns = minColumns;
            }));
    }

    [Fact]
    public void AddPdfParser_OcrEnabledWithEmptyTessDataPath_Throws()
    {
        var services = new ServiceCollection();
        var builder = new RagBuilder(services);

        Assert.Throws<ArgumentException>(() =>
            builder.AddPdfParser(o =>
            {
                o.UseOcrFallback = true;
                o.TessDataPath = "  ";
            }));
    }
}
