<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rag.NET.VectorStores.Qdrant</RootNamespace>
    <PackageId>Rag.NET.VectorStores.Qdrant</PackageId>
    <Description>Qdrant vector store for Rag.NET</Description>
    <VerifiedBy>container</VerifiedBy>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rag.NET.Abstractions\Rag.NET.Abstractions.csproj" />
    <PackageReference Include="Qdrant.Client" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Rag.NET.VectorStores.Qdrant.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
