using Rag.NET.Models;
using Rag.NET.Parsers.Audio;
using Xunit;

namespace Rag.NET.Parsers.Audio.Tests;

/// <summary>
/// Transcribes a real WAV with the real Whisper model — the first time anything in this repository
/// has executed <c>AudioDocumentParser</c>'s transcription path.
/// </summary>
/// <remarks>
/// <para>
/// <b>Milestone 6, Phase 6.2.</b> Every other test in this project subclasses the parser and
/// overrides <c>TranscribeAsync</c> (<c>FakeAudioDocumentParser</c>,
/// <c>CapturingFakeParser</c>, <c>ThrowingFakeParser</c>), so the model has never been loaded and
/// no audio has ever been decoded. What those tests cover is the code <i>around</i> transcription —
/// which is worth covering, and is not the same thing as covering transcription.
/// </para>
/// <para>
/// <b>This package was misfiled.</b> The Milestone 6 allowlist records it as owing "a hosted
/// transcription model", which put it in Phase 6.1 behind a credential nobody has. It needs no
/// credential at all: <c>Whisper.net</c> runs <b>locally</b>, and the parser downloads a GGML model
/// through <c>WhisperGgmlDownloader</c> on first use. It is a 6.2 real-file case, and it was
/// blocked on a service that was never involved.
/// </para>
/// <para>
/// <b>Provenance of <c>Resources/sample-speech.wav</c>:</b> synthesised 2026-08-17 by
/// <b>Windows' own speech engine</b> (<c>System.Speech.Synthesis</c>, voice "Microsoft Zira
/// Desktop"), 16 kHz mono 16-bit, 6.8 s, 216,526 bytes. That producer is deliberately unrelated to
/// the consumer: the audio is written by Microsoft's synthesiser and read by Whisper, so a pass
/// means two independent implementations agree on the content. A fixture generated by the library
/// under test would only prove it round-trips itself — the same reasoning that replaced the Office
/// and ZIP fixtures.
/// </para>
/// <para>
/// <b>Gated on a provisioned model, and the gate is satisfiable.</b> The model is 141 MB. Letting
/// the parser fetch it would make this test download that much on every cold runner, so the test
/// skips unless <see cref="ModelDirectoryVariable"/> names a directory to cache it in. Provision it
/// with:
/// </para>
/// <code>
/// $env:RAGNET_WHISPER_MODEL_DIR = "$env:LOCALAPPDATA\ragnet-whisper"
/// dotnet test tests/Rag.NET.Parsers.Audio.Tests --filter RealTranscriptionTests
/// </code>
/// <para>
/// The first run downloads <c>ggml-base.bin</c> into that directory; later runs reuse it. Verified
/// 2026-08-17: the model downloaded (141 MB) and returned two segments —
/// "This is an integration test document." and "The quick brown fox jumps over the lazy dog."
/// </para>
/// </remarks>
public sealed class RealTranscriptionTests
{
    /// <summary>Names a writable directory for the GGML model cache. Absent means skip.</summary>
    public const string ModelDirectoryVariable = "RAGNET_WHISPER_MODEL_DIR";

    private const string SkipReason =
        "Set RAGNET_WHISPER_MODEL_DIR to a writable directory to run the real Whisper " +
        "transcription. The first run downloads ggml-base.bin (141 MB) into it; later runs reuse " +
        "it. Skipped rather than downloading unconditionally, because a cold runner would pay 141 " +
        "MB for one test.";

    private static string WavPath =>
        Path.Combine(AppContext.BaseDirectory, "Resources", "sample-speech.wav");

    private static DocumentMetadata Metadata() => new()
    {
        DocumentId = new DocumentId("speech-1"),
        FileName = "sample-speech.wav",
        ContentType = "audio/wav",
    };

    [Fact]
    public void TheFixtureShipsBesideTheTest()
    {
        // Guards the suite: a missing fixture would otherwise fail the transcription test for a
        // reason that has nothing to do with transcription.
        Assert.True(File.Exists(WavPath), $"sample-speech.wav was not copied to {WavPath}.");
    }

    [Fact]
    public async Task RealWhisper_TranscribesRealSpeechFromTheWav()
    {
        var modelDir = Environment.GetEnvironmentVariable(ModelDirectoryVariable);
        Assert.SkipWhen(string.IsNullOrWhiteSpace(modelDir), SkipReason);

        var sut = new AudioDocumentParser(new AudioParserOptions
        {
            Language = "en",
            ModelCacheDirectory = modelDir!,
        });

        await using var audio = File.OpenRead(WavPath);
        var sections = await sut
            .ParseAsync(audio, Metadata(), TestContext.Current.CancellationToken)
            .ToListAsync(TestContext.Current.CancellationToken);

        Assert.NotEmpty(sections);
        Assert.All(sections, s => Assert.False(string.IsNullOrWhiteSpace(s.Text)));

        var transcript = string.Join(" ", sections.Select(s => s.Text));

        // Content assertions, not "did not throw". A transcriber returning empty strings, or
        // silence, passes every non-emptiness check ever written — which is exactly how the
        // default chunker shipped one chunk per word while the suite stayed green.
        Assert.Contains("integration test document", transcript, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("quick brown fox", transcript, StringComparison.OrdinalIgnoreCase);
    }

    /// <remarks>
    /// Whisper returns timed segments, and the parser is supposed to preserve that. A transcriber
    /// that collapsed everything into one untimed blob would satisfy the content assertions above
    /// while destroying the only structure audio has.
    /// </remarks>
    [Fact]
    public async Task TheTranscriptKeepsItsSegmentStructure()
    {
        var modelDir = Environment.GetEnvironmentVariable(ModelDirectoryVariable);
        Assert.SkipWhen(string.IsNullOrWhiteSpace(modelDir), SkipReason);

        var sut = new AudioDocumentParser(new AudioParserOptions
        {
            Language = "en",
            ModelCacheDirectory = modelDir!,
        });

        await using var audio = File.OpenRead(WavPath);
        var sections = await sut
            .ParseAsync(audio, Metadata(), TestContext.Current.CancellationToken)
            .ToListAsync(TestContext.Current.CancellationToken);

        // The fixture is two sentences with a pause between them; Whisper segments on that pause.
        Assert.True(
            sections.Count >= 2,
            $"Expected at least two segments from two spoken sentences, got {sections.Count}: " +
            string.Join(" | ", sections.Select(s => s.Text)));

        Assert.All(sections, s => Assert.Equal("speech-1", s.DocumentId.Value));
    }
}
