using Azure.Storage.Blobs;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Containers;
using Rag.NET.DataProviders.AzureBlob;
using Xunit;

namespace Rag.NET.DataProviders.AzureBlob.IntegrationTests;

/// <summary>
/// Runs <see cref="AzureBlobDataProvider"/> against <b>Azurite</b>, Microsoft's own Azure Storage
/// emulator, in a container: real blobs uploaded over the real Azure SDK, then enumerated back.
/// </summary>
/// <remarks>
/// <para>
/// <b>Milestone 6, Phase 6.1.</b> The allowlist entry reads "Azure Blob Storage (Azurite is a
/// container option; decide in 6.1)". <b>The decision: take it.</b> Azurite is published by
/// Microsoft and implements the Blob REST API, which puts it in the same class as Pinecone's
/// <c>pinecone-local</c> — a vendor emulator, not a third-party reimplementation — and that is
/// already accepted as <c>container</c> elsewhere in this ledger.
/// </para>
/// <para>
/// <b>What this replaces.</b> <c>Rag.NET.DataProviders.AzureBlob.Tests</c> builds a
/// <see cref="BlobContainerClient"/> over a canned <c>HttpClientTransport</c> that returns a
/// hand-written <c>ListBlobs</c> XML payload. That is the transport replaced by the test — the
/// same shape as the <c>FakeHttpMessageHandler</c> the RSS provider was stuck behind, and the same
/// shape as fixtures generated by the library that reads them. It proves the provider can parse
/// XML this repository wrote. It cannot prove the provider can list a container.
/// </para>
/// <para>
/// The hand-written payload also carries only <c>&lt;Etag&gt;</c>: no <c>Last-Modified</c>, no
/// <c>Creation-Time</c>, no <c>Content-Length</c>. So every timestamp the provider maps was
/// unverified, which is exactly what the assertions below cover.
/// </para>
/// </remarks>
public sealed class AzuriteDataProviderTests : IAsyncLifetime
{
    private const string ContainerName = "ragnet-integration";

    // Azurite's well-known development credentials, published by Microsoft and identical on every
    // machine. Not a secret, and deliberately not read from configuration: a test that needs a
    // credential from somewhere is a test that will not run.
    private const string AccountName = "devstoreaccount1";
    private const string AccountKey =
        "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==";

    private readonly IContainer _azurite = new ContainerBuilder("mcr.microsoft.com/azure-storage/azurite:latest")
        .WithPortBinding(10000, true)
        .WithCommand("azurite-blob", "--blobHost", "0.0.0.0", "--skipApiVersionCheck")
        .WithWaitStrategy(Wait.ForUnixContainer().UntilMessageIsLogged("Blob service successfully listens"))
        .Build();

    private BlobContainerClient _container = null!;

    public async ValueTask InitializeAsync()
    {
        await _azurite.StartAsync(TestContext.Current.CancellationToken);

        var port = _azurite.GetMappedPublicPort(10000);
        var connectionString =
            "DefaultEndpointsProtocol=http;" +
            $"AccountName={AccountName};" +
            $"AccountKey={AccountKey};" +
            $"BlobEndpoint=http://127.0.0.1:{port}/{AccountName};";

        var service = new BlobServiceClient(connectionString);
        _container = service.GetBlobContainerClient(ContainerName);
        await _container.CreateIfNotExistsAsync(cancellationToken: TestContext.Current.CancellationToken);

        await UploadAsync("readme.md", "# Integration Test Document");
        await UploadAsync("docs/guide.md", "A blob under a path prefix.");
        await UploadAsync("docs/nested/deep.txt", "Three levels down.");
    }

    public async ValueTask DisposeAsync() => await _azurite.DisposeAsync();

    private async Task UploadAsync(string name, string content)
    {
        using var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(content));
        await _container.GetBlobClient(name).UploadAsync(
            stream, overwrite: true, cancellationToken: TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task EveryBlobInTheContainer_IsEnumerated()
    {
        var sut = new AzureBlobDataProvider(_container);

        var entries = await sut
            .GetFilesAsync(TestContext.Current.CancellationToken)
            .ToListAsync(TestContext.Current.CancellationToken);

        Assert.Equal(3, entries.Count);
        Assert.All(entries, e => Assert.True(e.IsSuccess));

        var paths = entries.Select(e => e.Value.Metadata!["path"].ToString()).ToList();
        Assert.Contains("readme.md", paths, StringComparer.Ordinal);
        Assert.Contains("docs/guide.md", paths, StringComparer.Ordinal);
        Assert.Contains("docs/nested/deep.txt", paths, StringComparer.Ordinal);
    }

    /// <remarks>
    /// The canned payload the unit tests use carries only an <c>Etag</c>, so <c>UpdatedAt</c> was
    /// never populated by anything and never asserted. A real server sets <c>Last-Modified</c> on
    /// every blob it accepts.
    /// </remarks>
    [Fact]
    public async Task EachEntry_CarriesTheTimestampsARealServerSets()
    {
        var sut = new AzureBlobDataProvider(_container);

        var entries = await sut
            .GetFilesAsync(TestContext.Current.CancellationToken)
            .ToListAsync(TestContext.Current.CancellationToken);

        Assert.All(entries, e =>
        {
            Assert.NotNull(e.Value.UpdatedAt);
            Assert.NotEqual(default, e.Value.UpdatedAt);
            Assert.False(string.IsNullOrWhiteSpace(e.Value.ETag), "a real blob always has an ETag");
        });
    }

    /// <remarks>
    /// The content fetch is a second real round trip, and the half a listing test never reaches.
    /// A provider that enumerated a container correctly and could not download a blob would pass
    /// every assertion above.
    /// </remarks>
    [Fact]
    public async Task FollowingAnEntry_DownloadsTheRealBlobContent()
    {
        var sut = new AzureBlobDataProvider(_container);

        var entries = await sut
            .GetFilesAsync(TestContext.Current.CancellationToken)
            .ToListAsync(TestContext.Current.CancellationToken);

        var readme = entries.Single(e =>
            string.Equals(e.Value.Metadata!["path"].ToString(), "readme.md", StringComparison.Ordinal));

        await using var content = await readme.Value.OpenContentAsync(TestContext.Current.CancellationToken);
        using var reader = new StreamReader(content);
        var body = await reader.ReadToEndAsync(TestContext.Current.CancellationToken);

        Assert.Equal("# Integration Test Document", body);
    }

    /// <remarks>
    /// A blob name is a flat string containing slashes, not a directory tree — the provider's own
    /// doc says <c>path</c> "is the only path a blob has". This asserts the nesting survives
    /// enumeration verbatim, and that <c>FileName</c> is the last segment rather than the whole key.
    /// </remarks>
    [Fact]
    public async Task ANestedBlobName_SurvivesAsAPathWithItsFileNameSplitOff()
    {
        var sut = new AzureBlobDataProvider(_container);

        var entries = await sut
            .GetFilesAsync(TestContext.Current.CancellationToken)
            .ToListAsync(TestContext.Current.CancellationToken);

        var deep = entries.Single(e =>
            string.Equals(e.Value.Metadata!["path"].ToString(), "docs/nested/deep.txt", StringComparison.Ordinal));

        Assert.Equal("deep.txt", deep.Value.FileName);
        Assert.Equal(ContainerName, deep.Value.Metadata!["container"].ToString());
    }
}
